# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PaymentSDK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PaymentSDK

  target 'PaymentSDKTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'UIHostApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UIHostApp

  target 'UIHostAppUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Swifter', '~> 1.4.6'
  end

end


target 'UIHostObjCApp' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    # Pods for UIHostApp

    target 'UIHostObjCAppUITests' do
        inherit! :search_paths
        # Pods for testing
        pod 'Swifter', '~> 1.4.6'
    end

end
